session_name: flexsmc-dev
windows:
- window_name: dev window
  layout: main-vertical
  options:
    main-pane-width: 90
  shell_command_before:
    - cd .
  panes:
    - shell_command:
      - FLEX_ROLE_GW=1 FLEX_ID=1 FLEX_IFACE=wlp4s0 ./startNode.sh
    - shell_command:
      - FLEX_ID=2 FLEX_SMCSOCK=unix:///tmp/grpc-flexsmc1.sock FLEX_IFACE=wlp4s0 ./startNode.sh 
    - shell_command:
      - FLEX_ID=3 FLEX_SMCSOCK=unix:///tmp/grpc-flexsmc2.sock FLEX_IFACE=wlp4s0 ./startNode.sh 
    - pwd
