// Code generated by protoc-gen-go.
// source: smc/smc.proto
// DO NOT EDIT!

/*
Package smc is a generated protocol buffer package.

It is generated from these files:
	smc/smc.proto

It has these top-level messages:
	SessionCtx
*/
package smc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import job "github.com/grandcat/flexsmc/proto/job"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SessionCtx struct {
	SessionID uint64 `protobuf:"varint,1,opt,name=sessionID" json:"sessionID,omitempty"`
}

func (m *SessionCtx) Reset()                    { *m = SessionCtx{} }
func (m *SessionCtx) String() string            { return proto.CompactTextString(m) }
func (*SessionCtx) ProtoMessage()               {}
func (*SessionCtx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterType((*SessionCtx)(nil), "smc.SessionCtx")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for SMC service

type SMCClient interface {
	Init(ctx context.Context, in *SessionCtx, opts ...grpc.CallOption) (*job.CmdResult, error)
	DoPrepare(ctx context.Context, in *job.PreparePhase, opts ...grpc.CallOption) (*job.CmdResult, error)
	DoSession(ctx context.Context, in *job.SessionPhase, opts ...grpc.CallOption) (*job.CmdResult, error)
	TearDown(ctx context.Context, in *SessionCtx, opts ...grpc.CallOption) (*job.CmdResult, error)
}

type sMCClient struct {
	cc *grpc.ClientConn
}

func NewSMCClient(cc *grpc.ClientConn) SMCClient {
	return &sMCClient{cc}
}

func (c *sMCClient) Init(ctx context.Context, in *SessionCtx, opts ...grpc.CallOption) (*job.CmdResult, error) {
	out := new(job.CmdResult)
	err := grpc.Invoke(ctx, "/smc.SMC/Init", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sMCClient) DoPrepare(ctx context.Context, in *job.PreparePhase, opts ...grpc.CallOption) (*job.CmdResult, error) {
	out := new(job.CmdResult)
	err := grpc.Invoke(ctx, "/smc.SMC/DoPrepare", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sMCClient) DoSession(ctx context.Context, in *job.SessionPhase, opts ...grpc.CallOption) (*job.CmdResult, error) {
	out := new(job.CmdResult)
	err := grpc.Invoke(ctx, "/smc.SMC/DoSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sMCClient) TearDown(ctx context.Context, in *SessionCtx, opts ...grpc.CallOption) (*job.CmdResult, error) {
	out := new(job.CmdResult)
	err := grpc.Invoke(ctx, "/smc.SMC/TearDown", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SMC service

type SMCServer interface {
	Init(context.Context, *SessionCtx) (*job.CmdResult, error)
	DoPrepare(context.Context, *job.PreparePhase) (*job.CmdResult, error)
	DoSession(context.Context, *job.SessionPhase) (*job.CmdResult, error)
	TearDown(context.Context, *SessionCtx) (*job.CmdResult, error)
}

func RegisterSMCServer(s *grpc.Server, srv SMCServer) {
	s.RegisterService(&_SMC_serviceDesc, srv)
}

func _SMC_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionCtx)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SMCServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/smc.SMC/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SMCServer).Init(ctx, req.(*SessionCtx))
	}
	return interceptor(ctx, in, info, handler)
}

func _SMC_DoPrepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(job.PreparePhase)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SMCServer).DoPrepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/smc.SMC/DoPrepare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SMCServer).DoPrepare(ctx, req.(*job.PreparePhase))
	}
	return interceptor(ctx, in, info, handler)
}

func _SMC_DoSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(job.SessionPhase)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SMCServer).DoSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/smc.SMC/DoSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SMCServer).DoSession(ctx, req.(*job.SessionPhase))
	}
	return interceptor(ctx, in, info, handler)
}

func _SMC_TearDown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionCtx)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SMCServer).TearDown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/smc.SMC/TearDown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SMCServer).TearDown(ctx, req.(*SessionCtx))
	}
	return interceptor(ctx, in, info, handler)
}

var _SMC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "smc.SMC",
	HandlerType: (*SMCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _SMC_Init_Handler,
		},
		{
			MethodName: "DoPrepare",
			Handler:    _SMC_DoPrepare_Handler,
		},
		{
			MethodName: "DoSession",
			Handler:    _SMC_DoSession_Handler,
		},
		{
			MethodName: "TearDown",
			Handler:    _SMC_TearDown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("smc/smc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0xce, 0x4d, 0xd6,
	0x07, 0x62, 0xbd, 0x82, 0xa2, 0xfc, 0x92, 0x7c, 0x21, 0x66, 0x20, 0x53, 0x4a, 0x3f, 0x3d, 0xb3,
	0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0x3f, 0xbd, 0x28, 0x31, 0x2f, 0x25, 0x39, 0xb1,
	0x44, 0x3f, 0x2d, 0x27, 0xb5, 0x02, 0xa4, 0x16, 0xac, 0x4e, 0x3f, 0x2b, 0x3f, 0x09, 0x84, 0x21,
	0xba, 0x94, 0xb4, 0xb8, 0xb8, 0x82, 0x53, 0x8b, 0x8b, 0x33, 0xf3, 0xf3, 0x9c, 0x4b, 0x2a, 0x84,
	0x64, 0xb8, 0x38, 0x8b, 0x21, 0x3c, 0x4f, 0x17, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x96, 0x20, 0x84,
	0x80, 0xd1, 0x61, 0x46, 0x2e, 0xe6, 0x60, 0x5f, 0x67, 0x21, 0x4d, 0x2e, 0x16, 0xcf, 0xbc, 0xcc,
	0x12, 0x21, 0x7e, 0x3d, 0x90, 0xed, 0x08, 0xed, 0x52, 0x7c, 0x7a, 0x20, 0x83, 0x9d, 0x73, 0x53,
	0x82, 0x52, 0x8b, 0x4b, 0x73, 0x4a, 0x94, 0x18, 0x84, 0x0c, 0xb8, 0x38, 0x5d, 0xf2, 0x03, 0x8a,
	0x52, 0x0b, 0x12, 0x8b, 0x52, 0x85, 0x04, 0xc1, 0xd2, 0x50, 0x5e, 0x40, 0x46, 0x62, 0x71, 0x2a,
	0x2e, 0x1d, 0x50, 0x33, 0xa1, 0x3a, 0xa0, 0x3c, 0x5c, 0x3a, 0x74, 0xb9, 0x38, 0x42, 0x52, 0x13,
	0x8b, 0x5c, 0xf2, 0xcb, 0xf3, 0x88, 0x70, 0x92, 0x93, 0x31, 0x97, 0x44, 0x4a, 0xb6, 0x5e, 0x22,
	0x30, 0x4c, 0x80, 0xc1, 0x53, 0x94, 0xa8, 0x97, 0x56, 0x94, 0x5a, 0x9c, 0x9c, 0xaf, 0x97, 0x92,
	0x9a, 0x9b, 0xef, 0xc4, 0xef, 0x91, 0x9a, 0x93, 0x93, 0x1f, 0x9e, 0x5f, 0x94, 0x93, 0x12, 0x00,
	0x0a, 0x9e, 0x00, 0xc6, 0x45, 0x4c, 0xcc, 0x1e, 0x3e, 0xe1, 0x49, 0x6c, 0xe0, 0xd0, 0x32, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x66, 0x34, 0xeb, 0x74, 0x01, 0x00, 0x00,
}
