// Code generated by protoc-gen-go.
// source: gateway.proto
// DO NOT EDIT!

/*
Package flexsmc is a generated protocol buffer package.

It is generated from these files:
	gateway.proto

It has these top-level messages:
	SMCInfo
	SMCCmd
	CmdResult
	SMCResult
*/
package flexsmc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import job "github.com/grandcat/flexsmc/proto/job"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MetadataKey int32

const (
	MetadataKey_PEERID MetadataKey = 0
)

var MetadataKey_name = map[int32]string{
	0: "PEERID",
}
var MetadataKey_value = map[string]int32{
	"PEERID": 0,
}

func (x MetadataKey) String() string {
	return proto.EnumName(MetadataKey_name, int32(x))
}
func (MetadataKey) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SMCCmd_Phase int32

const (
	SMCCmd_PREPARE SMCCmd_Phase = 0
	SMCCmd_SESSION SMCCmd_Phase = 1
	// ...
	SMCCmd_FINISH SMCCmd_Phase = 126
	SMCCmd_ABORT  SMCCmd_Phase = 127
)

var SMCCmd_Phase_name = map[int32]string{
	0:   "PREPARE",
	1:   "SESSION",
	126: "FINISH",
	127: "ABORT",
}
var SMCCmd_Phase_value = map[string]int32{
	"PREPARE": 0,
	"SESSION": 1,
	"FINISH":  126,
	"ABORT":   127,
}

func (x SMCCmd_Phase) String() string {
	return proto.EnumName(SMCCmd_Phase_name, int32(x))
}
func (SMCCmd_Phase) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type CmdResult_Status int32

const (
	CmdResult_SUCCESS     CmdResult_Status = 0
	CmdResult_UNKNOWN_CMD CmdResult_Status = 1
	CmdResult_DENIED      CmdResult_Status = 2
	CmdResult_ABORTED     CmdResult_Status = 3
	// Communication related errors
	CmdResult_STREAM_ERR CmdResult_Status = 128
)

var CmdResult_Status_name = map[int32]string{
	0:   "SUCCESS",
	1:   "UNKNOWN_CMD",
	2:   "DENIED",
	3:   "ABORTED",
	128: "STREAM_ERR",
}
var CmdResult_Status_value = map[string]int32{
	"SUCCESS":     0,
	"UNKNOWN_CMD": 1,
	"DENIED":      2,
	"ABORTED":     3,
	"STREAM_ERR":  128,
}

func (x CmdResult_Status) String() string {
	return proto.EnumName(CmdResult_Status_name, int32(x))
}
func (CmdResult_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type SMCInfo struct {
	// tcpport
	Tcpport uint32 `protobuf:"varint,1,opt,name=tcpport" json:"tcpport,omitempty"`
}

func (m *SMCInfo) Reset()                    { *m = SMCInfo{} }
func (m *SMCInfo) String() string            { return proto.CompactTextString(m) }
func (*SMCInfo) ProtoMessage()               {}
func (*SMCInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SMCCmd struct {
	SessionID uint64       `protobuf:"varint,1,opt,name=sessionID" json:"sessionID,omitempty"`
	State     SMCCmd_Phase `protobuf:"varint,2,opt,name=state,enum=flexsmc.SMCCmd_Phase" json:"state,omitempty"`
	// Payload packet
	//
	// Types that are valid to be assigned to Payload:
	//	*SMCCmd_Prepare
	//	*SMCCmd_Session
	Payload isSMCCmd_Payload `protobuf_oneof:"payload"`
}

func (m *SMCCmd) Reset()                    { *m = SMCCmd{} }
func (m *SMCCmd) String() string            { return proto.CompactTextString(m) }
func (*SMCCmd) ProtoMessage()               {}
func (*SMCCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type isSMCCmd_Payload interface {
	isSMCCmd_Payload()
}

type SMCCmd_Prepare struct {
	Prepare *job.Prepare `protobuf:"bytes,3,opt,name=prepare,oneof"`
}
type SMCCmd_Session struct {
	Session *job.SessionPhase `protobuf:"bytes,4,opt,name=session,oneof"`
}

func (*SMCCmd_Prepare) isSMCCmd_Payload() {}
func (*SMCCmd_Session) isSMCCmd_Payload() {}

func (m *SMCCmd) GetPayload() isSMCCmd_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *SMCCmd) GetPrepare() *job.Prepare {
	if x, ok := m.GetPayload().(*SMCCmd_Prepare); ok {
		return x.Prepare
	}
	return nil
}

func (m *SMCCmd) GetSession() *job.SessionPhase {
	if x, ok := m.GetPayload().(*SMCCmd_Session); ok {
		return x.Session
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*SMCCmd) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _SMCCmd_OneofMarshaler, _SMCCmd_OneofUnmarshaler, _SMCCmd_OneofSizer, []interface{}{
		(*SMCCmd_Prepare)(nil),
		(*SMCCmd_Session)(nil),
	}
}

func _SMCCmd_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*SMCCmd)
	// payload
	switch x := m.Payload.(type) {
	case *SMCCmd_Prepare:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Prepare); err != nil {
			return err
		}
	case *SMCCmd_Session:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Session); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("SMCCmd.Payload has unexpected type %T", x)
	}
	return nil
}

func _SMCCmd_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*SMCCmd)
	switch tag {
	case 3: // payload.prepare
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(job.Prepare)
		err := b.DecodeMessage(msg)
		m.Payload = &SMCCmd_Prepare{msg}
		return true, err
	case 4: // payload.session
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(job.SessionPhase)
		err := b.DecodeMessage(msg)
		m.Payload = &SMCCmd_Session{msg}
		return true, err
	default:
		return false, nil
	}
}

func _SMCCmd_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*SMCCmd)
	// payload
	switch x := m.Payload.(type) {
	case *SMCCmd_Prepare:
		s := proto.Size(x.Prepare)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SMCCmd_Session:
		s := proto.Size(x.Session)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type CmdResult struct {
	Status CmdResult_Status `protobuf:"varint,1,opt,name=status,enum=flexsmc.CmdResult_Status" json:"status,omitempty"`
	Msg    string           `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Result *SMCResult       `protobuf:"bytes,3,opt,name=result" json:"result,omitempty"`
	// Partly filled on receiver side (e.g. peer ID)
	Metadata map[string]string `protobuf:"bytes,7,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *CmdResult) Reset()                    { *m = CmdResult{} }
func (m *CmdResult) String() string            { return proto.CompactTextString(m) }
func (*CmdResult) ProtoMessage()               {}
func (*CmdResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CmdResult) GetResult() *SMCResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *CmdResult) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type SMCResult struct {
	Res float64 `protobuf:"fixed64,1,opt,name=res" json:"res,omitempty"`
}

func (m *SMCResult) Reset()                    { *m = SMCResult{} }
func (m *SMCResult) String() string            { return proto.CompactTextString(m) }
func (*SMCResult) ProtoMessage()               {}
func (*SMCResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*SMCInfo)(nil), "flexsmc.SMCInfo")
	proto.RegisterType((*SMCCmd)(nil), "flexsmc.SMCCmd")
	proto.RegisterType((*CmdResult)(nil), "flexsmc.CmdResult")
	proto.RegisterType((*SMCResult)(nil), "flexsmc.SMCResult")
	proto.RegisterEnum("flexsmc.MetadataKey", MetadataKey_name, MetadataKey_value)
	proto.RegisterEnum("flexsmc.SMCCmd_Phase", SMCCmd_Phase_name, SMCCmd_Phase_value)
	proto.RegisterEnum("flexsmc.CmdResult_Status", CmdResult_Status_name, CmdResult_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Gateway service

type GatewayClient interface {
	Ping(ctx context.Context, in *SMCInfo, opts ...grpc.CallOption) (*CmdResult, error)
	// A peer can open multiple streams if it has enough capacities.
	AwaitSMCRound(ctx context.Context, opts ...grpc.CallOption) (Gateway_AwaitSMCRoundClient, error)
}

type gatewayClient struct {
	cc *grpc.ClientConn
}

func NewGatewayClient(cc *grpc.ClientConn) GatewayClient {
	return &gatewayClient{cc}
}

func (c *gatewayClient) Ping(ctx context.Context, in *SMCInfo, opts ...grpc.CallOption) (*CmdResult, error) {
	out := new(CmdResult)
	err := grpc.Invoke(ctx, "/flexsmc.Gateway/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) AwaitSMCRound(ctx context.Context, opts ...grpc.CallOption) (Gateway_AwaitSMCRoundClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Gateway_serviceDesc.Streams[0], c.cc, "/flexsmc.Gateway/AwaitSMCRound", opts...)
	if err != nil {
		return nil, err
	}
	x := &gatewayAwaitSMCRoundClient{stream}
	return x, nil
}

type Gateway_AwaitSMCRoundClient interface {
	Send(*CmdResult) error
	Recv() (*SMCCmd, error)
	grpc.ClientStream
}

type gatewayAwaitSMCRoundClient struct {
	grpc.ClientStream
}

func (x *gatewayAwaitSMCRoundClient) Send(m *CmdResult) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gatewayAwaitSMCRoundClient) Recv() (*SMCCmd, error) {
	m := new(SMCCmd)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Gateway service

type GatewayServer interface {
	Ping(context.Context, *SMCInfo) (*CmdResult, error)
	// A peer can open multiple streams if it has enough capacities.
	AwaitSMCRound(Gateway_AwaitSMCRoundServer) error
}

func RegisterGatewayServer(s *grpc.Server, srv GatewayServer) {
	s.RegisterService(&_Gateway_serviceDesc, srv)
}

func _Gateway_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SMCInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flexsmc.Gateway/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).Ping(ctx, req.(*SMCInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_AwaitSMCRound_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GatewayServer).AwaitSMCRound(&gatewayAwaitSMCRoundServer{stream})
}

type Gateway_AwaitSMCRoundServer interface {
	Send(*SMCCmd) error
	Recv() (*CmdResult, error)
	grpc.ServerStream
}

type gatewayAwaitSMCRoundServer struct {
	grpc.ServerStream
}

func (x *gatewayAwaitSMCRoundServer) Send(m *SMCCmd) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gatewayAwaitSMCRoundServer) Recv() (*CmdResult, error) {
	m := new(CmdResult)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Gateway_serviceDesc = grpc.ServiceDesc{
	ServiceName: "flexsmc.Gateway",
	HandlerType: (*GatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Gateway_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AwaitSMCRound",
			Handler:       _Gateway_AwaitSMCRound_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("gateway.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 558 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x93, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0xc7, 0xe3, 0xbc, 0xf9, 0xf1, 0xe4, 0x49, 0x6b, 0x46, 0x20, 0xb9, 0x11, 0x88, 0xc8, 0x5c,
	0xa2, 0x22, 0x1c, 0x08, 0x97, 0xaa, 0x70, 0xc9, 0x8b, 0xa1, 0x56, 0x15, 0xc7, 0x5a, 0xb7, 0xe2,
	0x58, 0x6d, 0x12, 0x37, 0x0d, 0x24, 0x76, 0x64, 0xaf, 0x29, 0xb9, 0x00, 0x5f, 0x8f, 0x8f, 0xc3,
	0x37, 0x60, 0x77, 0xbd, 0x09, 0x05, 0x7a, 0xb0, 0xb4, 0x33, 0xf3, 0xdb, 0x9d, 0xff, 0xfc, 0xbd,
	0x0b, 0xcd, 0x05, 0x65, 0xd1, 0x2d, 0xdd, 0x3a, 0x9b, 0x34, 0x61, 0x09, 0xea, 0xd7, 0xab, 0xe8,
	0x4b, 0xb6, 0x9e, 0xb5, 0xba, 0x8b, 0x25, 0xbb, 0xc9, 0xa7, 0xce, 0x2c, 0x59, 0x77, 0x17, 0x29,
	0x8d, 0xe7, 0x33, 0xca, 0xba, 0xaa, 0xd8, 0x95, 0x6c, 0xf7, 0x63, 0x32, 0x15, 0x5f, 0xb1, 0xd3,
	0x7e, 0x06, 0x7a, 0x38, 0x1e, 0x7a, 0xf1, 0x75, 0x82, 0x16, 0xe8, 0x6c, 0xb6, 0xd9, 0x24, 0x29,
	0xb3, 0xb4, 0xb6, 0xd6, 0x69, 0x92, 0x5d, 0x68, 0xff, 0xd4, 0xa0, 0xce, 0xa9, 0xe1, 0x7a, 0x8e,
	0x8f, 0xc1, 0xc8, 0xa2, 0x2c, 0x5b, 0x26, 0xb1, 0x37, 0x92, 0x58, 0x95, 0xfc, 0x4e, 0xe0, 0x73,
	0xa8, 0x65, 0x8c, 0x2b, 0xb3, 0xca, 0xbc, 0x72, 0xd0, 0x7b, 0xe4, 0xa8, 0xd6, 0x4e, 0xb1, 0xdb,
	0x09, 0x6e, 0x68, 0x16, 0x91, 0x82, 0xc1, 0x0e, 0xe8, 0x9b, 0x34, 0xda, 0xd0, 0x34, 0xb2, 0x2a,
	0x1c, 0x6f, 0xf4, 0xfe, 0x77, 0x84, 0xae, 0xa0, 0xc8, 0x9d, 0x95, 0xc8, 0xae, 0x8c, 0x2f, 0x40,
	0x57, 0x3d, 0xac, 0xaa, 0x24, 0x1f, 0x48, 0x32, 0x2c, 0x72, 0xf2, 0x50, 0x81, 0x2b, 0xc6, 0x3e,
	0x81, 0x9a, 0xcc, 0x61, 0x03, 0xf4, 0x80, 0xb8, 0x41, 0x9f, 0xb8, 0x66, 0x49, 0x04, 0xa1, 0x1b,
	0x86, 0xde, 0xc4, 0x37, 0x35, 0x04, 0xa8, 0xbf, 0xf3, 0x7c, 0x2f, 0x3c, 0x33, 0xbf, 0xa2, 0x01,
	0xb5, 0xfe, 0x60, 0x42, 0x2e, 0xcc, 0x6f, 0x03, 0x83, 0x4b, 0xa2, 0xdb, 0x55, 0x42, 0xe7, 0xf6,
	0x8f, 0x32, 0x18, 0x5c, 0x32, 0x89, 0xb2, 0x7c, 0xc5, 0xf0, 0x15, 0xd4, 0x85, 0xe8, 0x3c, 0x93,
	0x33, 0x1f, 0xf4, 0x8e, 0xf6, 0x93, 0xed, 0x19, 0x27, 0x94, 0x00, 0x51, 0x20, 0x9a, 0x50, 0x59,
	0x67, 0x0b, 0xe9, 0x84, 0x41, 0xc4, 0x12, 0x8f, 0xa1, 0x9e, 0x4a, 0x54, 0xcd, 0x8b, 0x77, 0xed,
	0x29, 0x0e, 0x21, 0x8a, 0xc0, 0xb7, 0xf0, 0xdf, 0x3a, 0x62, 0x74, 0x4e, 0x19, 0xb5, 0xf4, 0x76,
	0x85, 0xd3, 0xed, 0x7b, 0x5a, 0x8e, 0x15, 0xe2, 0xc6, 0x2c, 0xdd, 0x92, 0xfd, 0x8e, 0xd6, 0x1b,
	0x68, 0xfe, 0x51, 0x12, 0x62, 0x3e, 0x45, 0x5b, 0x29, 0x9e, 0x8b, 0xe1, 0x4b, 0x7c, 0x08, 0xb5,
	0xcf, 0x74, 0x95, 0x47, 0x4a, 0x60, 0x11, 0x9c, 0x96, 0x4f, 0x34, 0x3b, 0xe0, 0x3f, 0xbb, 0x18,
	0x41, 0x58, 0x76, 0x39, 0x1c, 0x72, 0xd7, 0xb8, 0x7f, 0x87, 0xd0, 0xb8, 0xf4, 0xcf, 0xfd, 0xc9,
	0x07, 0xff, 0x6a, 0x38, 0x1e, 0x15, 0x1e, 0x8e, 0x5c, 0xdf, 0x73, 0x47, 0x66, 0x59, 0x90, 0xd2,
	0x43, 0x1e, 0x54, 0x38, 0x09, 0xe1, 0x05, 0x71, 0xfb, 0xe3, 0x2b, 0x97, 0x10, 0xf3, 0xbb, 0x66,
	0x3f, 0x01, 0x63, 0x3f, 0xa1, 0x90, 0xc2, 0x67, 0x94, 0x52, 0x34, 0x22, 0x96, 0xc7, 0x47, 0xd0,
	0xd8, 0xa9, 0x3d, 0xe7, 0xca, 0xf8, 0xb9, 0x81, 0xeb, 0x12, 0x6f, 0x64, 0x96, 0x7a, 0x39, 0xe8,
	0xef, 0x8b, 0x9b, 0x8e, 0x0e, 0x54, 0x83, 0x65, 0xbc, 0x40, 0xf3, 0xae, 0x6b, 0xe2, 0xe2, 0xb6,
	0xf0, 0x5f, 0x67, 0xec, 0x12, 0x9e, 0x42, 0xb3, 0x7f, 0x4b, 0x97, 0x4c, 0x74, 0x4e, 0xf2, 0x78,
	0x8e, 0xf7, 0x60, 0xad, 0xc3, 0xbf, 0x6e, 0xa8, 0x5d, 0xea, 0x68, 0x2f, 0xb5, 0xc1, 0x53, 0x40,
	0xfe, 0x82, 0x1c, 0xf5, 0x98, 0x14, 0x32, 0xd8, 0x49, 0x09, 0xb4, 0x69, 0x5d, 0xbe, 0x9e, 0xd7,
	0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x1e, 0x59, 0xbf, 0xb9, 0x88, 0x03, 0x00, 0x00,
}
