// Code generated by protoc-gen-go.
// source: gateway.proto
// DO NOT EDIT!

/*
Package flexsmc is a generated protocol buffer package.

It is generated from these files:
	gateway.proto

It has these top-level messages:
	SMCInfo
	SMCCmd
	SMCTask
	Prepare
	SessionPhase
	CmdResult
*/
package flexsmc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DataOrigin int32

const (
	DataOrigin_TEMPERATURE  DataOrigin = 0
	DataOrigin_HUMIDITY     DataOrigin = 1
	DataOrigin_AMBIENT      DataOrigin = 2
	DataOrigin_AIR_PRESSURE DataOrigin = 3
	DataOrigin_PRESENCE     DataOrigin = 10
	// Dynamically assigned sensor types.
	DataOrigin_RESERVED_999            DataOrigin = 999
	DataOrigin_DYNAMIC_ASSIGNMENT_1000 DataOrigin = 1000
	// ...
	DataOrigin_DYNAMIC_ASSIGNMENT_99999 DataOrigin = 99999
	DataOrigin_RESERVED_100000          DataOrigin = 100000
)

var DataOrigin_name = map[int32]string{
	0:      "TEMPERATURE",
	1:      "HUMIDITY",
	2:      "AMBIENT",
	3:      "AIR_PRESSURE",
	10:     "PRESENCE",
	999:    "RESERVED_999",
	1000:   "DYNAMIC_ASSIGNMENT_1000",
	99999:  "DYNAMIC_ASSIGNMENT_99999",
	100000: "RESERVED_100000",
}
var DataOrigin_value = map[string]int32{
	"TEMPERATURE":              0,
	"HUMIDITY":                 1,
	"AMBIENT":                  2,
	"AIR_PRESSURE":             3,
	"PRESENCE":                 10,
	"RESERVED_999":             999,
	"DYNAMIC_ASSIGNMENT_1000":  1000,
	"DYNAMIC_ASSIGNMENT_99999": 99999,
	"RESERVED_100000":          100000,
}

func (x DataOrigin) String() string {
	return proto.EnumName(DataOrigin_name, int32(x))
}
func (DataOrigin) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Aggregator int32

const (
	Aggregator_SUM           Aggregator = 0
	Aggregator_AVG           Aggregator = 1
	Aggregator_MEDIAN        Aggregator = 2
	Aggregator_STD_DEVIATION Aggregator = 3
)

var Aggregator_name = map[int32]string{
	0: "SUM",
	1: "AVG",
	2: "MEDIAN",
	3: "STD_DEVIATION",
}
var Aggregator_value = map[string]int32{
	"SUM":           0,
	"AVG":           1,
	"MEDIAN":        2,
	"STD_DEVIATION": 3,
}

func (x Aggregator) String() string {
	return proto.EnumName(Aggregator_name, int32(x))
}
func (Aggregator) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type MetadataKey int32

const (
	MetadataKey_PEERID MetadataKey = 0
)

var MetadataKey_name = map[int32]string{
	0: "PEERID",
}
var MetadataKey_value = map[string]int32{
	"PEERID": 0,
}

func (x MetadataKey) String() string {
	return proto.EnumName(MetadataKey_name, int32(x))
}
func (MetadataKey) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type SMCCmd_Phase int32

const (
	SMCCmd_INIT    SMCCmd_Phase = 0
	SMCCmd_PREPARE SMCCmd_Phase = 1
	SMCCmd_SESSION SMCCmd_Phase = 2
	// ...
	SMCCmd_FINISH SMCCmd_Phase = 126
	SMCCmd_ABORT  SMCCmd_Phase = 127
)

var SMCCmd_Phase_name = map[int32]string{
	0:   "INIT",
	1:   "PREPARE",
	2:   "SESSION",
	126: "FINISH",
	127: "ABORT",
}
var SMCCmd_Phase_value = map[string]int32{
	"INIT":    0,
	"PREPARE": 1,
	"SESSION": 2,
	"FINISH":  126,
	"ABORT":   127,
}

func (x SMCCmd_Phase) String() string {
	return proto.EnumName(SMCCmd_Phase_name, int32(x))
}
func (SMCCmd_Phase) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type CmdResult_Status int32

const (
	CmdResult_SUCCESS     CmdResult_Status = 0
	CmdResult_UNKNOWN_CMD CmdResult_Status = 1
	CmdResult_DENIED      CmdResult_Status = 2
	CmdResult_ABORTED     CmdResult_Status = 3
	// Communication related errors
	CmdResult_STREAM_ERR CmdResult_Status = 128
)

var CmdResult_Status_name = map[int32]string{
	0:   "SUCCESS",
	1:   "UNKNOWN_CMD",
	2:   "DENIED",
	3:   "ABORTED",
	128: "STREAM_ERR",
}
var CmdResult_Status_value = map[string]int32{
	"SUCCESS":     0,
	"UNKNOWN_CMD": 1,
	"DENIED":      2,
	"ABORTED":     3,
	"STREAM_ERR":  128,
}

func (x CmdResult_Status) String() string {
	return proto.EnumName(CmdResult_Status_name, int32(x))
}
func (CmdResult_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

type SMCInfo struct {
	// tcpport
	Tcpport uint32 `protobuf:"varint,1,opt,name=tcpport" json:"tcpport,omitempty"`
}

func (m *SMCInfo) Reset()                    { *m = SMCInfo{} }
func (m *SMCInfo) String() string            { return proto.CompactTextString(m) }
func (*SMCInfo) ProtoMessage()               {}
func (*SMCInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SMCCmd struct {
	SessionID uint64       `protobuf:"varint,1,opt,name=sessionID" json:"sessionID,omitempty"`
	State     SMCCmd_Phase `protobuf:"varint,2,opt,name=state,enum=flexsmc.SMCCmd_Phase" json:"state,omitempty"`
	// Payload packet
	//
	// Types that are valid to be assigned to Payload:
	//	*SMCCmd_Prepare
	//	*SMCCmd_Session
	Payload isSMCCmd_Payload `protobuf_oneof:"payload"`
}

func (m *SMCCmd) Reset()                    { *m = SMCCmd{} }
func (m *SMCCmd) String() string            { return proto.CompactTextString(m) }
func (*SMCCmd) ProtoMessage()               {}
func (*SMCCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type isSMCCmd_Payload interface {
	isSMCCmd_Payload()
}

type SMCCmd_Prepare struct {
	Prepare *Prepare `protobuf:"bytes,3,opt,name=prepare,oneof"`
}
type SMCCmd_Session struct {
	Session *SessionPhase `protobuf:"bytes,4,opt,name=session,oneof"`
}

func (*SMCCmd_Prepare) isSMCCmd_Payload() {}
func (*SMCCmd_Session) isSMCCmd_Payload() {}

func (m *SMCCmd) GetPayload() isSMCCmd_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *SMCCmd) GetPrepare() *Prepare {
	if x, ok := m.GetPayload().(*SMCCmd_Prepare); ok {
		return x.Prepare
	}
	return nil
}

func (m *SMCCmd) GetSession() *SessionPhase {
	if x, ok := m.GetPayload().(*SMCCmd_Session); ok {
		return x.Session
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*SMCCmd) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _SMCCmd_OneofMarshaler, _SMCCmd_OneofUnmarshaler, _SMCCmd_OneofSizer, []interface{}{
		(*SMCCmd_Prepare)(nil),
		(*SMCCmd_Session)(nil),
	}
}

func _SMCCmd_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*SMCCmd)
	// payload
	switch x := m.Payload.(type) {
	case *SMCCmd_Prepare:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Prepare); err != nil {
			return err
		}
	case *SMCCmd_Session:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Session); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("SMCCmd.Payload has unexpected type %T", x)
	}
	return nil
}

func _SMCCmd_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*SMCCmd)
	switch tag {
	case 3: // payload.prepare
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Prepare)
		err := b.DecodeMessage(msg)
		m.Payload = &SMCCmd_Prepare{msg}
		return true, err
	case 4: // payload.session
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SessionPhase)
		err := b.DecodeMessage(msg)
		m.Payload = &SMCCmd_Session{msg}
		return true, err
	default:
		return false, nil
	}
}

func _SMCCmd_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*SMCCmd)
	// payload
	switch x := m.Payload.(type) {
	case *SMCCmd_Prepare:
		s := proto.Size(x.Prepare)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SMCCmd_Session:
		s := proto.Size(x.Session)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type SMCTask struct {
	Set    string     `protobuf:"bytes,1,opt,name=Set,json=set" json:"Set,omitempty"`
	Source DataOrigin `protobuf:"varint,2,opt,name=source,enum=flexsmc.DataOrigin" json:"source,omitempty"`
	// (Pre)Selectors
	Aggregator      Aggregator                 `protobuf:"varint,4,opt,name=aggregator,enum=flexsmc.Aggregator" json:"aggregator,omitempty"`
	TicketSignature string                     `protobuf:"bytes,7,opt,name=ticketSignature" json:"ticketSignature,omitempty"`
	Issued          *google_protobuf.Timestamp `protobuf:"bytes,8,opt,name=issued" json:"issued,omitempty"`
	QuerySignature  string                     `protobuf:"bytes,9,opt,name=querySignature" json:"querySignature,omitempty"`
}

func (m *SMCTask) Reset()                    { *m = SMCTask{} }
func (m *SMCTask) String() string            { return proto.CompactTextString(m) }
func (*SMCTask) ProtoMessage()               {}
func (*SMCTask) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SMCTask) GetIssued() *google_protobuf.Timestamp {
	if m != nil {
		return m.Issued
	}
	return nil
}

type Prepare struct {
	Participants []*Prepare_Participant `protobuf:"bytes,1,rep,name=participants" json:"participants,omitempty"`
	SmcTask      *SMCTask               `protobuf:"bytes,2,opt,name=smcTask" json:"smcTask,omitempty"`
}

func (m *Prepare) Reset()                    { *m = Prepare{} }
func (m *Prepare) String() string            { return proto.CompactTextString(m) }
func (*Prepare) ProtoMessage()               {}
func (*Prepare) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Prepare) GetParticipants() []*Prepare_Participant {
	if m != nil {
		return m.Participants
	}
	return nil
}

func (m *Prepare) GetSmcTask() *SMCTask {
	if m != nil {
		return m.SmcTask
	}
	return nil
}

type Prepare_Participant struct {
	Identity string `protobuf:"bytes,1,opt,name=identity" json:"identity,omitempty"`
	Addr     string `protobuf:"bytes,2,opt,name=addr" json:"addr,omitempty"`
}

func (m *Prepare_Participant) Reset()                    { *m = Prepare_Participant{} }
func (m *Prepare_Participant) String() string            { return proto.CompactTextString(m) }
func (*Prepare_Participant) ProtoMessage()               {}
func (*Prepare_Participant) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type SessionPhase struct {
}

func (m *SessionPhase) Reset()                    { *m = SessionPhase{} }
func (m *SessionPhase) String() string            { return proto.CompactTextString(m) }
func (*SessionPhase) ProtoMessage()               {}
func (*SessionPhase) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type CmdResult struct {
	Status CmdResult_Status `protobuf:"varint,1,opt,name=status,enum=flexsmc.CmdResult_Status" json:"status,omitempty"`
	Msg    string           `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	// Partly filled on receiver side (e.g. peer ID)
	Metadata map[string]string `protobuf:"bytes,3,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *CmdResult) Reset()                    { *m = CmdResult{} }
func (m *CmdResult) String() string            { return proto.CompactTextString(m) }
func (*CmdResult) ProtoMessage()               {}
func (*CmdResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CmdResult) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterType((*SMCInfo)(nil), "flexsmc.SMCInfo")
	proto.RegisterType((*SMCCmd)(nil), "flexsmc.SMCCmd")
	proto.RegisterType((*SMCTask)(nil), "flexsmc.SMCTask")
	proto.RegisterType((*Prepare)(nil), "flexsmc.Prepare")
	proto.RegisterType((*Prepare_Participant)(nil), "flexsmc.Prepare.Participant")
	proto.RegisterType((*SessionPhase)(nil), "flexsmc.SessionPhase")
	proto.RegisterType((*CmdResult)(nil), "flexsmc.CmdResult")
	proto.RegisterEnum("flexsmc.DataOrigin", DataOrigin_name, DataOrigin_value)
	proto.RegisterEnum("flexsmc.Aggregator", Aggregator_name, Aggregator_value)
	proto.RegisterEnum("flexsmc.MetadataKey", MetadataKey_name, MetadataKey_value)
	proto.RegisterEnum("flexsmc.SMCCmd_Phase", SMCCmd_Phase_name, SMCCmd_Phase_value)
	proto.RegisterEnum("flexsmc.CmdResult_Status", CmdResult_Status_name, CmdResult_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Gateway service

type GatewayClient interface {
	Ping(ctx context.Context, in *SMCInfo, opts ...grpc.CallOption) (*CmdResult, error)
	// A peer can open multiple streams if it has enough capacities.
	AwaitSMCRound(ctx context.Context, opts ...grpc.CallOption) (Gateway_AwaitSMCRoundClient, error)
}

type gatewayClient struct {
	cc *grpc.ClientConn
}

func NewGatewayClient(cc *grpc.ClientConn) GatewayClient {
	return &gatewayClient{cc}
}

func (c *gatewayClient) Ping(ctx context.Context, in *SMCInfo, opts ...grpc.CallOption) (*CmdResult, error) {
	out := new(CmdResult)
	err := grpc.Invoke(ctx, "/flexsmc.Gateway/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) AwaitSMCRound(ctx context.Context, opts ...grpc.CallOption) (Gateway_AwaitSMCRoundClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Gateway_serviceDesc.Streams[0], c.cc, "/flexsmc.Gateway/AwaitSMCRound", opts...)
	if err != nil {
		return nil, err
	}
	x := &gatewayAwaitSMCRoundClient{stream}
	return x, nil
}

type Gateway_AwaitSMCRoundClient interface {
	Send(*CmdResult) error
	Recv() (*SMCCmd, error)
	grpc.ClientStream
}

type gatewayAwaitSMCRoundClient struct {
	grpc.ClientStream
}

func (x *gatewayAwaitSMCRoundClient) Send(m *CmdResult) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gatewayAwaitSMCRoundClient) Recv() (*SMCCmd, error) {
	m := new(SMCCmd)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Gateway service

type GatewayServer interface {
	Ping(context.Context, *SMCInfo) (*CmdResult, error)
	// A peer can open multiple streams if it has enough capacities.
	AwaitSMCRound(Gateway_AwaitSMCRoundServer) error
}

func RegisterGatewayServer(s *grpc.Server, srv GatewayServer) {
	s.RegisterService(&_Gateway_serviceDesc, srv)
}

func _Gateway_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SMCInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flexsmc.Gateway/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).Ping(ctx, req.(*SMCInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_AwaitSMCRound_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GatewayServer).AwaitSMCRound(&gatewayAwaitSMCRoundServer{stream})
}

type Gateway_AwaitSMCRoundServer interface {
	Send(*SMCCmd) error
	Recv() (*CmdResult, error)
	grpc.ServerStream
}

type gatewayAwaitSMCRoundServer struct {
	grpc.ServerStream
}

func (x *gatewayAwaitSMCRoundServer) Send(m *SMCCmd) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gatewayAwaitSMCRoundServer) Recv() (*CmdResult, error) {
	m := new(CmdResult)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Gateway_serviceDesc = grpc.ServiceDesc{
	ServiceName: "flexsmc.Gateway",
	HandlerType: (*GatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Gateway_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AwaitSMCRound",
			Handler:       _Gateway_AwaitSMCRound_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("gateway.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 900 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x94, 0xdd, 0x8e, 0xdb, 0x44,
	0x14, 0xc7, 0xe3, 0x24, 0x1b, 0x27, 0x27, 0xc9, 0xae, 0x3b, 0x50, 0x91, 0x46, 0x15, 0xad, 0x82,
	0x84, 0xaa, 0x05, 0xb9, 0xdb, 0xf4, 0x86, 0x2d, 0x54, 0xc2, 0x89, 0xcd, 0xae, 0x55, 0xd9, 0x6b,
	0x8d, 0x9d, 0x45, 0xbd, 0x8a, 0xbc, 0xc9, 0xac, 0x6b, 0x6d, 0x12, 0x07, 0x7b, 0x4c, 0xc9, 0x0d,
	0x20, 0x71, 0xdd, 0x47, 0x40, 0xf0, 0x14, 0x5c, 0xf3, 0x36, 0xf0, 0x18, 0x9c, 0xf1, 0x47, 0x92,
	0x5d, 0x36, 0x37, 0xf1, 0xcc, 0xfc, 0xce, 0xc7, 0x9c, 0xf3, 0x3f, 0x03, 0xdd, 0xc0, 0xe7, 0xec,
	0xbd, 0xbf, 0x51, 0xd7, 0x71, 0xc4, 0x23, 0x22, 0x5f, 0x2f, 0xd8, 0x4f, 0xc9, 0x72, 0xd6, 0x7f,
	0x12, 0x44, 0x51, 0xb0, 0x60, 0xcf, 0xb3, 0xed, 0xab, 0xf4, 0xfa, 0x39, 0x0f, 0x97, 0x2c, 0xe1,
	0xfe, 0x72, 0x9d, 0x93, 0x83, 0xcf, 0x40, 0x76, 0xad, 0xb1, 0xb9, 0xba, 0x8e, 0x48, 0x0f, 0x64,
	0x3e, 0x5b, 0xaf, 0xa3, 0x98, 0xf7, 0xa4, 0xa7, 0xd2, 0xb3, 0x2e, 0x2d, 0x97, 0x83, 0xdf, 0xaa,
	0xd0, 0x40, 0x6a, 0xbc, 0x9c, 0x93, 0xc7, 0xd0, 0x4a, 0x58, 0x92, 0x84, 0xd1, 0xca, 0xd4, 0x33,
	0xac, 0x4e, 0x77, 0x1b, 0xe4, 0x0b, 0x38, 0x40, 0xe7, 0x9c, 0xf5, 0xaa, 0x78, 0x72, 0x38, 0x7c,
	0xa8, 0x16, 0x79, 0xa8, 0xb9, 0xb5, 0xea, 0xbc, 0xf3, 0x13, 0x46, 0x73, 0x86, 0x7c, 0x09, 0xf2,
	0x3a, 0x66, 0x6b, 0x3f, 0x66, 0xbd, 0x1a, 0xe2, 0xed, 0xa1, 0xb2, 0xc5, 0x9d, 0x7c, 0xff, 0xbc,
	0x42, 0x4b, 0x84, 0xbc, 0x00, 0xb9, 0x88, 0xd3, 0xab, 0x67, 0xf4, 0x9e, 0xf3, 0x7c, 0x3f, 0x73,
	0x2e, 0x4c, 0x0a, 0x6e, 0x30, 0x82, 0x83, 0x6c, 0x8f, 0x34, 0xa1, 0x6e, 0xda, 0xa6, 0xa7, 0x54,
	0x48, 0x1b, 0x64, 0x87, 0x1a, 0x8e, 0x46, 0x0d, 0x45, 0x12, 0x0b, 0xd7, 0x70, 0x5d, 0xf3, 0xc2,
	0x56, 0xaa, 0x04, 0xa0, 0xf1, 0x1d, 0x42, 0xee, 0xb9, 0xf2, 0x33, 0x69, 0xc1, 0x81, 0x36, 0xba,
	0xa0, 0x9e, 0xf2, 0xcb, 0xa8, 0x85, 0x49, 0xfa, 0x9b, 0x45, 0xe4, 0xcf, 0x45, 0x15, 0x44, 0xad,
	0x3c, 0x3f, 0xb9, 0x21, 0x0a, 0xd4, 0x5c, 0x96, 0xd7, 0xa9, 0x45, 0x6b, 0x09, 0xe3, 0x78, 0xf5,
	0x46, 0x12, 0xa5, 0xf1, 0xac, 0xbc, 0xfb, 0x47, 0xdb, 0xf4, 0x74, 0x9f, 0xfb, 0x17, 0x71, 0x18,
	0x84, 0x2b, 0x5a, 0x20, 0xe4, 0x25, 0x80, 0x1f, 0x04, 0x31, 0xc3, 0xae, 0x45, 0x71, 0x76, 0x9f,
	0x7d, 0x03, 0x6d, 0x7b, 0x44, 0xf7, 0x30, 0xf2, 0x0c, 0x8e, 0x78, 0x38, 0xbb, 0x61, 0xdc, 0x0d,
	0x83, 0x95, 0xcf, 0x53, 0xac, 0x9b, 0x9c, 0xc5, 0xbf, 0xbb, 0x4d, 0x86, 0xd0, 0x08, 0x93, 0x24,
	0x65, 0xf3, 0x5e, 0x33, 0x2b, 0x55, 0x5f, 0xcd, 0x65, 0xa0, 0x96, 0x32, 0x50, 0xbd, 0x52, 0x06,
	0xb4, 0x20, 0xc9, 0xe7, 0x70, 0xf8, 0x43, 0xca, 0xe2, 0xcd, 0xce, 0x79, 0x2b, 0x73, 0x7e, 0x67,
	0x77, 0xf0, 0x97, 0x84, 0x25, 0x2c, 0x7a, 0xf2, 0x2d, 0x74, 0xf0, 0x1f, 0xa3, 0x87, 0x6b, 0x7f,
	0xc5, 0x13, 0x2c, 0x47, 0x0d, 0xa3, 0x3d, 0xbe, 0xdb, 0x46, 0xd5, 0xd9, 0x41, 0xf4, 0x96, 0x05,
	0x39, 0xc6, 0xae, 0x2e, 0x67, 0xa2, 0xa4, 0x59, 0xd9, 0xf6, 0x35, 0x50, 0x94, 0x9a, 0x96, 0x40,
	0xff, 0x35, 0xb4, 0xf7, 0x1c, 0x91, 0x3e, 0x34, 0xc3, 0x39, 0x5b, 0xf1, 0x90, 0x6f, 0x8a, 0x3e,
	0x6c, 0xd7, 0x84, 0x40, 0xdd, 0x9f, 0xcf, 0xe3, 0xcc, 0x67, 0x8b, 0x66, 0xdf, 0x83, 0x43, 0xe8,
	0xec, 0x0b, 0x65, 0xf0, 0x7b, 0x15, 0x5a, 0xa8, 0x49, 0xca, 0x92, 0x74, 0xc1, 0x51, 0x5e, 0x0d,
	0xa1, 0xca, 0x34, 0xc9, 0x7c, 0x1d, 0x0e, 0x1f, 0x6d, 0xf3, 0xd8, 0x32, 0xaa, 0x9b, 0x01, 0xb4,
	0x00, 0x85, 0x06, 0x96, 0x49, 0x50, 0xc4, 0x10, 0x9f, 0xe4, 0x1b, 0x68, 0x2e, 0x19, 0xf7, 0xe7,
	0xd8, 0x70, 0x94, 0xb4, 0xa8, 0xc5, 0xd3, 0x7b, 0xdc, 0x58, 0x05, 0x62, 0xac, 0x78, 0xbc, 0xa1,
	0x5b, 0x8b, 0xfe, 0xd7, 0xd0, 0xbd, 0x75, 0x24, 0x02, 0xdc, 0xb0, 0xf2, 0x72, 0xe2, 0x93, 0x7c,
	0x0c, 0x07, 0x3f, 0xfa, 0x8b, 0x94, 0x15, 0x41, 0xf3, 0xc5, 0xab, 0xea, 0x57, 0xd2, 0xc0, 0xc1,
	0x09, 0xcd, 0xd3, 0x12, 0xaa, 0x9e, 0x8c, 0xc7, 0x28, 0x6c, 0xd4, 0xfb, 0x11, 0xb4, 0x27, 0xf6,
	0x1b, 0xfb, 0xe2, 0x7b, 0x7b, 0x3a, 0xb6, 0x74, 0xd4, 0x3c, 0xca, 0x5c, 0x37, 0x6c, 0xd3, 0xd0,
	0x51, 0xf2, 0x48, 0x66, 0x32, 0xc7, 0x45, 0x0d, 0x49, 0x70, 0x3d, 0x6a, 0x68, 0xd6, 0xd4, 0xa0,
	0x54, 0xf9, 0x55, 0x3a, 0xfe, 0x5b, 0x02, 0xd8, 0x49, 0x57, 0x78, 0xf2, 0x0c, 0xcb, 0x31, 0xa8,
	0xe6, 0x4d, 0x70, 0x7a, 0x2a, 0xa4, 0x03, 0xcd, 0xf3, 0x89, 0x65, 0xea, 0xa6, 0xf7, 0x36, 0x9f,
	0x25, 0xcd, 0x1a, 0x99, 0x86, 0xed, 0xa1, 0x63, 0x05, 0x3a, 0x9a, 0x49, 0xa7, 0x38, 0x69, 0xae,
	0x2b, 0xe0, 0x9a, 0x80, 0xc5, 0xca, 0xb0, 0xc7, 0x86, 0x02, 0xe4, 0x01, 0x74, 0xc4, 0x82, 0x5e,
	0x1a, 0xfa, 0xf4, 0xf4, 0xf4, 0x54, 0xf9, 0x47, 0xc6, 0x77, 0xe5, 0x13, 0xfd, 0xad, 0xad, 0x59,
	0xe6, 0x78, 0xaa, 0xe1, 0x48, 0x9e, 0xd9, 0x16, 0xba, 0x9a, 0xbe, 0x38, 0x39, 0x39, 0x51, 0xfe,
	0x95, 0xc9, 0xa7, 0xd0, 0xbb, 0xe7, 0xf4, 0x54, 0xfc, 0x94, 0x3f, 0x3e, 0x34, 0xc8, 0x43, 0x38,
	0xda, 0x3a, 0x14, 0x36, 0x68, 0xf5, 0xe7, 0x87, 0xc6, 0xf1, 0x6b, 0x80, 0xdd, 0x2c, 0x11, 0x19,
	0x67, 0x76, 0x62, 0x61, 0xe6, 0xf8, 0xa1, 0x5d, 0x9e, 0xe5, 0xc5, 0xb0, 0x0c, 0xdd, 0xd4, 0xc4,
	0xfc, 0x3f, 0x80, 0xae, 0xeb, 0xe9, 0x53, 0xdd, 0xb8, 0x34, 0x35, 0x4f, 0x3c, 0x09, 0xb5, 0xe3,
	0x47, 0xd0, 0x2e, 0x1b, 0xf2, 0x06, 0x8b, 0x8f, 0xb4, 0x63, 0x18, 0xd4, 0xd4, 0x95, 0xca, 0x30,
	0x05, 0xf9, 0x2c, 0x7f, 0x71, 0x89, 0x0a, 0x75, 0x27, 0x5c, 0x05, 0xe4, 0x96, 0x72, 0xc5, 0x83,
	0xda, 0x27, 0xff, 0x6f, 0xfe, 0xa0, 0x42, 0x5e, 0x41, 0x57, 0x7b, 0xef, 0x87, 0x1c, 0x29, 0x1a,
	0xa5, 0xab, 0x39, 0xb9, 0x07, 0xeb, 0x1f, 0xdd, 0x79, 0x39, 0x07, 0x95, 0x67, 0xd2, 0x89, 0x34,
	0x7a, 0x02, 0x64, 0x16, 0x2d, 0xd5, 0x20, 0xe4, 0xef, 0xd2, 0xab, 0x12, 0x19, 0x95, 0xa9, 0x38,
	0xd2, 0x55, 0x23, 0x9b, 0xf0, 0x97, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x52, 0x5f, 0xcf, 0x3c,
	0x10, 0x06, 0x00, 0x00,
}
